application: dart-lang
version: CHANGEME
# NOTE: URL is CHANGEME.dart-lang.appspot.com
#       To specify a name, change 'CHANGEME' to something
#       like 'prod-zone-article'.
#
#       To deploy to dartlang.org (only from a clean master workspace)
#       change CHANGEME to a date string: YYYY-MM-DD.
#       For more information on making changes, see goto/dartsiteupdate.
#
# IMPORTANT: AFTER changing the version, DO THIS:
#       make clean
#       make build

runtime: python27
api_version: 1
threadsafe: true

pagespeed:
  enabled_rewriters:
    - InlineImages
    - CollapseWhitespace
    - RemoveComments
    - InlineJs
  url_blacklist:
    - http://www.dartlang.org/*/code/out/*
    - https://www.dartlang.org/*/code/out/*

#default_expiration: "1d"

handlers:
- url: /community/
  script: scripts.redirector.application

- url: /\+
  script: scripts.redirector.application

- url: /docs/tutorials/web-ui/
  script: scripts.redirector.application

- url: /docs/tutorials/templates/
  script: scripts.redirector.application

- url: /docs/tutorials/custom-elements/
  script: scripts.redirector.application

- url: /docs/dart-up-and-running/ch0\d.html
  script: scripts.redirector.application

- url: /docs/dart-up-and-running/contents/ch04-tools-dartdoc.html
  script: scripts.redirector.application

- url: /mailing-list
  script: scripts.redirector.application

- url: /docs/spec/dartLangSpec.*
  script: scripts.redirector.application

- url: /docs/getting-started/editor/.*
  script: scripts.redirector.application

- url: /downloads.html
  script: scripts.redirector.application

- url: /docs/language-tour.*
  script: scripts.redirector.application

- url: /docs/library-tour.*
  script: scripts.redirector.application

- url: /docs/pub-package-manager.*
  script: scripts.redirector.application

- url: /tools/dartdoc/
  script: scripts.redirector.application

- url: /editor.*
  script: scripts.redirector.application

- url: /docs/editor/getting-started/
  script: scripts.redirector.application

- url: /docs/dart2js/
  script: scripts.redirector.application

- url: /docs/standalone-dart-vm/
  script: scripts.redirector.application

- url: /news.*
  script: scripts.redirector.application

- url: /atom.xml
  script: scripts.redirector.application

- url: /docs/api/.*
  script: scripts.redirector.application

- url: /eclipse/
  script: scripts.redirector.application

- url: /dartium/.*
  script: scripts.redirector.application

- url: /tools/analyzer
  script: scripts.redirector.application

- url: /docs/editor/.*
  script: scripts.redirector.application

- url: /docs/sdk/.*
  script: scripts.redirector.application

- url: /language-tour/.*
  script: scripts.redirector.application

- url: /docs/technical-overview.*
  script: scripts.redirector.application

- url: /docs/getting-started/sdk/.*
  script: scripts.redirector.application

- url: /resources/
  script: scripts.redirector.application

- url: /articles/using-future-based-apis/
  script: scripts.redirector.application

- url: /articles/feet-wet-streams/
  script: scripts.redirector.application

- url: /articles/profiling/
  script: scripts.redirector.application

- url: /articles/dart-web-components/.*
  script: scripts.redirector.application

- url: /articles/m1-language-changes/.*
  script: scripts.redirector.application

- url: /articles/m2-whats-new/.*
  script: scripts.redirector.application

- url: /articles/m3-whats-new/.*
  script: scripts.redirector.application

- url: /articles/dart-js/.*
  script: scripts.redirector.application

- url: /dartisans/podcast-feed
  script: scripts.redirector.application

- url: /hangouts.*
  script: scripts.redirector.application

- url: /docs/cookbook/
  script: scripts.redirector.application

- url: /codelab
  script: scripts.redirector.application

- url: /codelabs/web-ui-writer/codelab.pdf
  script: scripts.redirector.application

- url: /codelabs/web-ui-writer/
  script: scripts.redirector.application

- url: /eclipse/update.*
  script: scripts.redirector.application

- url: /events/2013/flight-school/
  script: scripts.redirector.application

- url: /is-dartisans-live-now
  script: scripts.is_dartisans_live.application

- url: /dartisans-live-config
  script: scripts.is_dartisans_live.application
  login: admin

- url: /bundles
  expiration: 7d
  static_dir: static/bundles

- url: /(.*\.png)
  static_files: static/\1
  expiration: 1d
  upload: static/(.*\.png)

- url: /(.*\.ico)
  static_files: static/\1
  expiration: 7d
  upload: static/(.*\.ico)

- url: /(.*\.jpg)
  static_files: static/\1
  expiration: 1d
  upload: static/(.*\.jpg)

- url: /(.*\.woff)
  static_files: static/\1
  expiration: 7d
  upload: static/(.*\.woff)

- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html
  secure: always

- url: (.*\..*)
  static_files: static\1
  upload: static
  secure: always

- url: .*
  script: scripts.redirector.application
