// Auto-generated from clickcount.html.
// DO NOT EDIT.

library clickcount_html;

import 'dart:html' as autogenerated;
import 'package:web_components/watcher.dart' as autogenerated;

int count = 0;
void increment(e) { count++; }
main() {}

/** Generated code. */
autogenerated.Element ___e0;

autogenerated.EventListener _listener_click_1;

autogenerated.Element ___e1;

autogenerated.WatcherDisposer _stopWatcher___e1_2;

/** Create the views and bind them to models. */
void init_autogenerated() {
  // Create view.
  var _root = new autogenerated.DocumentFragment.html(_INITIAL_PAGE);
  
  // Initialize fields.
  ___e0 = _root.query('#__e-0');
  
  ___e1 = _root.query('#__e-1');
  
  // Attach model to views.
  _listener_click_1 = (e) {
    increment(e);
    autogenerated.dispatch();
  };
  ___e0.on.click.add(_listener_click_1);
  
  _stopWatcher___e1_2 = autogenerated.watchAndInvoke(() => count, (e) {
    ___e1.innerHTML = '(click count: ${count})';
  });
  
  // Attach view to the document.
  autogenerated.document.body.nodes.add(_root);
}

final String _INITIAL_PAGE = r'''
<div class="well">
<button data-action="click:increment" id="__e-0">Click me</button>
<span id="__e-1">(click count: {{count}})</span>
</div>
''';

