// Auto-generated from counter.html.
// DO NOT EDIT.

library counter_html;

import 'dart:html' as autogenerated;
import 'package:web_components/watcher.dart' as autogenerated;

import 'dart:html' as html;
import 'package:web_components/watcher.dart' as watchers;
int count;
main() {
  count = 0;
  html.window.setInterval(() {
    count++;
    watchers.dispatch();
  }, 1000);
}

/** Generated code. */
autogenerated.Element ___e0;

autogenerated.WatcherDisposer _stopWatcher___e0_1;

/** Create the views and bind them to models. */
void init_autogenerated() {
  // Create view.
  var _root = new autogenerated.DocumentFragment.html(_INITIAL_PAGE);
  
  // Initialize fields.
  ___e0 = _root.query('#__e-0');
  
  // Attach model to views.
  _stopWatcher___e0_1 = autogenerated.watchAndInvoke(() => count, (e) {
    ___e0.innerHTML = 'Hello counter: ${count}';
  });
  
  // Attach view to the document.
  autogenerated.document.body.nodes.add(_root);
}

final String _INITIAL_PAGE = r'''
<div class="well" id="__e-0">Hello counter: {{count}}</div>
''';

