// Auto-generated from countcomponent.html.
// DO NOT EDIT.

library countcomponent_html;

import 'dart:html' as autogenerated;
import 'package:web_components/watcher.dart' as autogenerated;

import 'countcomponent.html.dart';
import 'countcomponent.html.x_click_counter.dart';

main(){}

/** Generated code. */
autogenerated.Element ___e2;

/** Create the views and bind them to models. */
void init_autogenerated() {
  // Create view.
  var _root = new autogenerated.DocumentFragment.html(_INITIAL_PAGE);
  
  // Initialize fields.
  ___e2 = _root.query('#__e-2');
  
  var component___e2 = new CounterComponent.forElement(___e2);
  
  component___e2.created_autogenerated();
  
  // Attach model to views.
  ___e2.xtag.inserted_autogenerated();
  
  // Attach view to the document.
  autogenerated.document.body.nodes.add(_root);
}

final String _INITIAL_PAGE = r'''
<div class="well">
<div is="x-click-counter" id="__e-2"></div>
</div>
''';

