// Auto-generated from countcomponent.html.
// DO NOT EDIT.

library x_click_counter;

import 'dart:html' as autogenerated;
import 'package:web_components/watcher.dart' as autogenerated;

import 'package:web_components/web_component.dart';

class CounterComponent extends WebComponent {
  
  /** Autogenerated from the template. */
  
  /**
  * Shadow root for this component. We use 'var' to allow simulating shadow DOM
  * on browsers that don't support this feature.
  */
  var _root;
  autogenerated.Element ___e0;
  
  autogenerated.EventListener _listener_click_1;
  
  autogenerated.Element ___e1;
  
  autogenerated.WatcherDisposer _stopWatcher___e1_2;
  
  CounterComponent.forElement(e) : super.forElement(e) {
    _root = createShadowRoot();
  }
  
  void created_autogenerated() {
    _root.innerHTML = r'''
    <div>
    <button data-action="click:increment" id="__e-0">Click me</button>
    <span id="__e-1">(click count: {{count}})</span>
    </div>
    ''';
    
    ___e0 = _root.query('#__e-0');
    
    ___e1 = _root.query('#__e-1');
    
    // Call user-defined created();
    created();
  }
  
  void inserted_autogenerated() {
    _listener_click_1 = (e) {
      increment(e);
      autogenerated.dispatch();
    };
    ___e0.on.click.add(_listener_click_1);
    
    _stopWatcher___e1_2 = autogenerated.watchAndInvoke(() => count, (e) {
      ___e1.innerHTML = '(click count: ${count})';
    });
    
    // Call user-defined inserted();
    inserted();
  }
  
  void removed_autogenerated() {
    // Call user-defined removed();
    removed();
    
    ___e0.on.click.remove(_listener_click_1);
    _listener_click_1 = null;
    
    _stopWatcher___e1_2();
    
  }
  
  /** Original code from the component. */
  
  int count = 0;
  void increment(e) { count++; }
}

