// Auto-generated from countcomponent5.html.
// DO NOT EDIT.

library countcomponent5_html;

import 'dart:html' as autogenerated;
import 'package:web_components/watcher.dart' as autogenerated;

import 'countcomponent5.html.dart';
import 'countcomponent5.html.x_click_counter.dart';

int myNumber = 12;
main(){}

/** Generated code. */
autogenerated.Element ___e2;

autogenerated.Element ___e3;

/** Create the views and bind them to models. */
void init_autogenerated() {
  // Create view.
  var _root = new autogenerated.DocumentFragment.html(_INITIAL_PAGE);
  
  // Initialize fields.
  ___e2 = _root.query('#__e-2');
  
  var component___e2 = new CounterComponent.forElement(___e2);
  
  component___e2.count =  myNumber;
  
  component___e2.created_autogenerated();
  
  ___e3 = _root.query('#__e-3');
  
  var component___e3 = new CounterComponent.forElement(___e3);
  
  component___e3.count =  5;
  
  component___e3.created_autogenerated();
  
  // Attach model to views.
  ___e2.xtag.inserted_autogenerated();
  
  ___e3.xtag.inserted_autogenerated();
  
  // Attach view to the document.
  autogenerated.document.body.nodes.add(_root);
}

final String _INITIAL_PAGE = r'''
<div class="well">
<div is="x-click-counter" data-value="count: myNumber" id="__e-2"></div>
<div is="x-click-counter" data-value="count: 5" id="__e-3"></div>
</div>
''';

