// Auto-generated from helloworld.html.
// DO NOT EDIT.

library helloworld_html;

import 'dart:html' as autogenerated;
import 'package:web_components/watcher.dart' as autogenerated;

String dataValue;
main() {
  var today = new Date.now();
  dataValue = 'world ${today.year}-${today.month}-${today.day}';
}

/** Generated code. */
autogenerated.Element ___e0;

autogenerated.WatcherDisposer _stopWatcher___e0_1;

/** Create the views and bind them to models. */
void init_autogenerated() {
  // Create view.
  var _root = new autogenerated.DocumentFragment.html(_INITIAL_PAGE);
  
  // Initialize fields.
  ___e0 = _root.query('#__e-0');
  
  // Attach model to views.
  _stopWatcher___e0_1 = autogenerated.watchAndInvoke(() => dataValue, (e) {
    ___e0.innerHTML = 'Hello ${dataValue}!';
  });
  
  // Attach view to the document.
  autogenerated.document.body.nodes.add(_root);
}

final String _INITIAL_PAGE = r'''
<div class="well" id="__e-0">Hello {{dataValue}}!</div>
''';

