// Auto-generated from matchstrings.html.
// DO NOT EDIT.

library matchstrings_html;

import 'dart:html' as autogenerated;
import 'package:web_components/watcher.dart' as autogenerated;

String str1 = '';
String str2 = '';
main() {}

/** Generated code. */
autogenerated.InputElement ___e0;

autogenerated.EventListener _listener_input_1;

autogenerated.WatcherDisposer _stopWatcher___e0_2;

autogenerated.InputElement ___e1;

autogenerated.EventListener _listener_input_3;

autogenerated.WatcherDisposer _stopWatcher___e1_4;

autogenerated.Element ___e2;

// Fields for template conditional '__e-2'
autogenerated.WatcherDisposer _stopWatcher_if___e2;
autogenerated.Element _childTemplate___e2;
autogenerated.Element _parent___e2;
autogenerated.Element _child___e2;
String _childId___e2;

/** Create the views and bind them to models. */
void init_autogenerated() {
  // Create view.
  var _root = new autogenerated.DocumentFragment.html(_INITIAL_PAGE);
  
  // Initialize fields.
  ___e0 = _root.query('#__e-0');
  
  ___e1 = _root.query('#__e-1');
  
  ___e2 = _root.query('#__e-2');
  
  assert(___e2.elements.length == 1);
  _childTemplate___e2 = ___e2.elements[0];
  _childId___e2 = _childTemplate___e2.id;
  if (_childId___e2 != null && _childId___e2 != '') {
    _childTemplate___e2.id = '';
  }
  ___e2.style.display = 'none';
  ___e2.nodes.clear();
  
  // Attach model to views.
  _listener_input_1 = (e) {
    str1 = ___e0.value;
    autogenerated.dispatch();
  };
  ___e0.on.input.add(_listener_input_1);
  
  _stopWatcher___e0_2 = autogenerated.watchAndInvoke(() => str1, (e) {
    ___e0.value = e.newValue;
  });
  
  _listener_input_3 = (e) {
    str2 = ___e1.value;
    autogenerated.dispatch();
  };
  ___e1.on.input.add(_listener_input_3);
  
  _stopWatcher___e1_4 = autogenerated.watchAndInvoke(() => str2, (e) {
    ___e1.value = e.newValue;
  });
  
  _stopWatcher_if___e2 = autogenerated.watchAndInvoke(() => str1 == str2, (e) {
    bool showNow = e.newValue;
    if (_child___e2 != null && !showNow) {
      // Remove any listeners/watchers on children
      
      // Remove the actual child
      _child___e2.remove();
      _child___e2 = null;
    } else if (_child___e2 == null && showNow) {
      _child___e2 = _childTemplate___e2.clone(true);
      if (_childId___e2 != null && _childId___e2 != '') {
        _child___e2.id = _childId___e2;
      }
      // Initialize children
      
      ___e2.parent.nodes.add(_child___e2);
      
      // Attach listeners/watchers
      
    }
  });
  
  // Attach view to the document.
  autogenerated.document.body.nodes.add(_root);
}

final String _INITIAL_PAGE = r'''
<div class="well">
<div> Input1: <input type="text" data-bind="value:str1" id="__e-0"></div>
<div> Input2: <input type="text" data-bind="value:str2" id="__e-1"></div>
<template instantiate="if str1 == str2" id="__e-2">
<div>They match!</div>
</template>
</div>
''';

