// Auto-generated from redbox.html.
// DO NOT EDIT.

library redbox_html;

import 'dart:html' as autogenerated;
import 'package:web_components/watcher.dart' as autogenerated;

import 'redbox.html.dart';
import 'redbox.html.x_redbox.dart';

main(){}

/** Generated code. */
autogenerated.Element ___e0;

/** Create the views and bind them to models. */
void init_autogenerated() {
  // Create view.
  var _root = new autogenerated.DocumentFragment.html(_INITIAL_PAGE);
  
  // Initialize fields.
  ___e0 = _root.query('#__e-0');
  
  var component___e0 = new RedBox.forElement(___e0);
  
  component___e0.created_autogenerated();
  
  // Attach model to views.
  ___e0.xtag.inserted_autogenerated();
  
  // Attach view to the document.
  autogenerated.document.body.nodes.add(_root);
}

final String _INITIAL_PAGE = r'''
<!-- TODO(sigmund): add this example to explainer document once we have this
feature working (issue #62). -->

<div class="well">
<x-redbox id="__e-0">
<span>hi</span>
</x-redbox>
</div>
''';

