// Auto-generated from redbox.html.
// DO NOT EDIT.

library x_redbox;

import 'dart:html' as autogenerated;
import 'package:web_components/watcher.dart' as autogenerated;

import 'package:web_components/web_component.dart' as autogenerated;
class RedBox extends autogenerated.WebComponent {
  
  /** Autogenerated from the template. */
  
  /**
  * Shadow root for this component. We use 'var' to allow simulating shadow DOM
  * on browsers that don't support this feature.
  */
  var _root;
  
  RedBox.forElement(e) : super.forElement(e) {
    _root = createShadowRoot();
  }
  
  void created_autogenerated() {
    _root.innerHTML = r'''
    <div style="border-color: red; border: 1px">
    <content></content>
    </div>
    ''';
    
    // Call user-defined created();
    created();
  }
  
  void inserted_autogenerated() {
    
    // Call user-defined inserted();
    inserted();
  }
  
  void removed_autogenerated() {
    // Call user-defined removed();
    removed();
    
  }
  
  /** Original code from the component. */
  
}

