// Auto-generated from twoway.html.
// DO NOT EDIT.

library twoway_html;

import 'dart:html' as autogenerated;
import 'package:web_components/watcher.dart' as autogenerated;

String str = '';
main() {}

/** Generated code. */
autogenerated.InputElement ___e0;

autogenerated.EventListener _listener_input_1;

autogenerated.WatcherDisposer _stopWatcher___e0_2;

autogenerated.Element ___e1;

autogenerated.WatcherDisposer _stopWatcher___e1_3;

autogenerated.Element ___e2;

autogenerated.WatcherDisposer _stopWatcher___e2_4;

/** Create the views and bind them to models. */
void init_autogenerated() {
  // Create view.
  var _root = new autogenerated.DocumentFragment.html(_INITIAL_PAGE);
  
  // Initialize fields.
  ___e0 = _root.query('#__e-0');
  
  ___e1 = _root.query('#__e-1');
  
  ___e2 = _root.query('#__e-2');
  
  // Attach model to views.
  _listener_input_1 = (e) {
    str = ___e0.value;
    autogenerated.dispatch();
  };
  ___e0.on.input.add(_listener_input_1);
  
  _stopWatcher___e0_2 = autogenerated.watchAndInvoke(() => str, (e) {
    ___e0.value = e.newValue;
  });
  
  _stopWatcher___e1_3 = autogenerated.watchAndInvoke(() => str, (e) {
    ___e1.innerHTML = ' Value: ${str}';
  });
  
  _stopWatcher___e2_4 = autogenerated.watchAndInvoke(() => str.length, (e) {
    ___e2.innerHTML = ' Length: ${str.length}';
  });
  
  // Attach view to the document.
  autogenerated.document.body.nodes.add(_root);
}

final String _INITIAL_PAGE = r'''
<div class="well">
Input:
<input type="text" data-bind="value:str" placeholder="type something here" id="__e-0">
<div id="__e-1"> Value: {{str}}</div>
<div id="__e-2"> Length: {{str.length}}</div>
</div>
''';

